version: '3'
services:
  neo4j:
    image: neo4j:4.1.1-enterprise
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - ./neo4j/plugins:/plugins
    - ./neo4j/data:/data
    environment:
      NEO4J_AUTH: neo4j/Passw0rd!
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
